# Generated by Buildfy v3.0
# 2026-09-10T16:22:53.588Z
import customtkinter as ctk
import tkinter as tk

# ── Theme ──────────────────────────────────────────────
BG_MAIN = "#0F0F11"
BG_CARD = "#1A1A1F"
BG_WIDGET = "#242429"
BORDER = "#2E2E36"
TEXT = "#F2F2F3"
TEXT_MUTED = "#8B8B99"
ACCENT = "#F0525C"
ACCENT_HOVER = "#E03E48"

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")


class App(ctk.CTk):
    # ── Setup ──────────────────────────────────────────────
    def __init__(self):
        super().__init__()
        self.title("My App")
        self.geometry("800x600")
        self.configure(fg_color=BG_MAIN)
        self.resizable(True, True)
        self._setup_widgets()
        self._setup_events()

    # ── Widgets ────────────────────────────────────────────
    def _setup_widgets(self):
        self._Sidebar_h58m_x = 1
        self._Sidebar_h58m_y = -3
        self._Button_khn9_x = 368
        self._Button_khn9_y = 258
        self._Entry_juu3_x = 336
        self._Entry_juu3_y = 386
        self._TextBox_kz1t_x = 288
        self._TextBox_kz1t_y = 90
        self._Navbar_iq51_x = 181
        self._Navbar_iq51_y = 4
        self._OptionMenu_he0g_x = 363
        self._OptionMenu_he0g_y = 477
        self._Switch_d9hv_x = 541
        self._Switch_d9hv_y = 128
        self._Checkbox_koh0_x = 545
        self._Checkbox_koh0_y = 222
        self._Radiobutton_7pql_x = 553
        self._Radiobutton_7pql_y = 317
        self._Slider_tg9u_x = 269
        self._Slider_tg9u_y = 534
        self._ComboBox_pb81_x = 242
        self._ComboBox_pb81_y = 318
        self._Label_irw2_x = 538
        self._Label_irw2_y = 78

        # CTkSidebar -> CTkFrame
        self.Sidebar_h58m = ctk.CTkFrame(self, fg_color=BG_CARD, width=180, height=594, border_color=BORDER,
                                         border_width=1, corner_radius=12)
        self.Sidebar_h58m.place(x=1, y=-3)

        self.Button_khn9 = ctk.CTkButton(self, text="Button", fg_color=ACCENT, text_color="#ffffff", corner_radius=11,
                                         hover_color="#b22a99", font=("Arial", 14), anchor="center", width=120,
                                         height=36)
        self.Button_khn9.place(x=368, y=258)

        self.Entry_juu3 = ctk.CTkEntry(self, placeholder_text="Enter text...", fg_color=BG_WIDGET, border_color=BORDER,
                                       text_color=TEXT, corner_radius=13, font=("Arial", 14), width=200, height=36,
                                       border_width=1, placeholder_text_color=TEXT_MUTED)
        self.Entry_juu3.place(x=336, y=386)

        self.TextBox_kz1t = ctk.CTkTextbox(self, fg_color=BG_WIDGET, text_color="#3c911d", corner_radius=8,
                                           font=("Arial", 14), width=200, height=120, border_width=1,
                                           border_color=BORDER)
        self.TextBox_kz1t.place(x=288, y=90)

        # CTkNavbar -> CTkFrame
        self.Navbar_iq51 = ctk.CTkFrame(self, fg_color=BG_CARD, width=621, height=48, border_color=BORDER,
                                        border_width=1, corner_radius=12)
        self.Navbar_iq51.place(x=181, y=4)

        self.OptionMenu_he0g = ctk.CTkOptionMenu(self, values=["Option 1", "Option 2"], fg_color="#7451f0",
                                                 button_color="#3ea2e0", width=180, height=32)
        self.OptionMenu_he0g.place(x=363, y=477)

        self.Switch_d9hv = ctk.CTkSwitch(self, text="Toggle", progress_color=ACCENT, text_color=TEXT,
                                         font=("Arial", 14), width=160, height=28)
        self.Switch_d9hv.place(x=541, y=128)

        self.Checkbox_koh0 = ctk.CTkCheckBox(self, text="Check me", fg_color=ACCENT, text_color=TEXT,
                                             font=("Arial", 14), width=140, height=28)
        self.Checkbox_koh0.place(x=545, y=222)

        self._Radiobutton_7pql_var = tk.IntVar(value=0)
        self.Radiobutton_7pql = ctk.CTkRadioButton(self, text="Option", fg_color=ACCENT, text_color=TEXT,
                                                   font=("Arial", 14), width=140, height=28,
                                                   variable=self._Radiobutton_7pql_var, value=1)
        self.Radiobutton_7pql.place(x=553, y=317)

        self.Slider_tg9u = ctk.CTkSlider(self, from_=0, to=100, button_color=ACCENT, progress_color=ACCENT,
                                         fg_color=BORDER, width=200, height=30)
        self.Slider_tg9u.place(x=269, y=534)
        self.Slider_tg9u.set(0.5)

        self.ComboBox_pb81 = ctk.CTkComboBox(self, values=["Option 1", "Option 2", "Option 3"], fg_color=BG_WIDGET,
                                             border_color=BORDER, width=180, height=36)
        self.ComboBox_pb81.place(x=242, y=318)

        self.Label_irw2 = ctk.CTkLabel(self, text="Label", text_color=TEXT, font=("Arial", 14), width=120, height=28)
        self.Label_irw2.place(x=538, y=78)

    # ── Events ─────────────────────────────────────────────
    def _setup_events(self):
        self.Button_khn9.configure(command=self._Button_khn9_click)

    def _Button_khn9_click(self):
        pass


def main():
    app = App()
    app.mainloop()


if __name__ == "__main__":
    main()